// Centralized list of all genres used across the app
// Source provided by user request (French labels preserved)
export const ALL_GENRES: string[] = [
  "Action",
  "Adolescence",
  "Aliens / Extra-terrestres",
  "Amitié",
  "Amour",
  "Apocalypse",
  "Art",
  "Arts martiaux",
  "Assassinat",
  "Autre monde",
  "Aventure",
  "Combats",
  "Comédie",
  "Crime",
  "Cyberpunk",
  "Danse",
  "Démons",
  "Détective",
  "Donghua",
  "Dragon",
  "Drame",
  "Ecchi",
  "Ecole",
  "Elfe",
  "Enquête",
  "Famille",
  "Fantastique",
  "Fantasy",
  "Fantômes",
  "Futur",
  "Gastronomie",
  "Ghibli",
  "Guerre",
  "Harcèlement",
  "Harem",
  "Harem inversé",
  "Histoire",
  "Historique",
  "Horreur",
  "Isekai",
  "Jeunesse",
  "Jeux",
  "Jeux vidéo",
  "Josei",
  "Journalisme",
  "Mafia",
  "Magical girl",
  "Magie",
  "Maladie",
  "Mariage",
  "Mature",
  "Mechas",
  "Médiéval",
  "Militaire",
  "Monde virtuel",
  "Monstres",
  "Musique",
  "Mystère",
  "Nekketsu",
  "Ninjas",
  "Nostalgie",
  "Paranormal",
  "Philosophie",
  "Pirates",
  "Police",
  "Politique",
  "Post-apocalyptique",
  "Pouvoirs psychiques",
  "Préhistoire",
  "Prison",
  "Psychologique",
  "Quotidien",
  "Religion",
  "Réincarnation / Transmigration",
  "Romance",
  "Samouraïs",
  "School Life",
  "Science-Fantasy",
  "Science-fiction",
  "Scientifique",
  "Seinen",
  "Shôjo",
  "Shôjo-Ai",
  "Shônen",
  "Shônen-Ai",
  "Slice of Life",
  "Société",
  "Sport",
  "Super pouvoirs",
  "Super-héros",
  "Surnaturel",
  "Survie",
  "Survival game",
  "Technologies",
  "Thriller",
  "Tournois",
  "Travail",
  "Vampires",
  "Vengeance",
  "Voyage",
  "Voyage temporel",
  "Webcomic",
  "Yakuza",
  "Yaoi",
  "Yokai",
  "Yuri",
];

// Optional: export a sorted copy for UI display
export const SORTED_GENRES = [...ALL_GENRES].sort((a, b) =>
  a.localeCompare(b, undefined, { sensitivity: "base" }),
);
