name: Build and push Docker image

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      - name: Extract version from tag
        id: meta
        run: |
          if [[ "${GITHUB_REF#refs/tags/}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: steps.meta.outputs.is_release == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/gazes-v2:${{ steps.meta.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/gazes-v2:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/gazes-v2:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/gazes-v2:cache,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.result == 'success'

    steps:
      - name: Deploy to VPS via Cloudflare Tunnel
        uses: dev-drprasad/cloudflared-ssh-run-remote-commands@v1
        with:
          host: ${{ secrets.CLOUDFLARE_TUNNEL_HOST }}
          username: ${{ secrets.SHH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          commands: |
            docker pull ghcr.io/${{ github.repository_owner }}/gazes-v2:latest
            docker stop gazes || true
            docker rm gazes || true
            docker run -d --restart=always --name gazes -p 3000:3000 -v gazes-data:/app/data ghcr.io/${{ github.repository_owner }}/gazes-v2:latest

